export enum AiReplyContextualEnum {
    VIEW_ID = "ai-quick-reply-view-id",
    TITLE = "Quick Ai Reply",
    CLOSE_BUTTON_LABEL = "Close",
    CLOSE_ACTION = "ai-reply-close-action-id",
    CLOSE_BLOCK = "ai-reply-close-block-id",
    GENERATE_BUTTON_LABEL = "Generate",
    GENERATE_BUTTON_ACTION = "ai-generate-action",
    GENERATE_BUTTON_BLOCK = "ai-reply-generate-block-id",
    SEND_BUTTON_LABEL = "Send",
    SEND_BUTTON_ACTION = "ai-send-action",
    SEND_BUTTON_BLOCK = "ai-send-block",
    PROMPT_LABEL = "Enter Your Prompt",
    PROMPT_ACTION = "ai-prompt-input-action",
    PROMPT_BLOCK = "ai-prompt-input-block",
    REPLY_LABEL = "Body of Quick Message",
    REPLY_ACTION = "ai-reply-message-body-action",
    REPLY_BLOCK = "ai-reply-message-body-block",
}
